notifications:
  email: false
services:
  - postgresql
addons:
  postgresql: "9.4"
language: go
go:
  - 1.9
before_install:
  - npm install -g jshint
  - go get -u github.com/golang/lint/golint
script:
  - jshint server/static/js/app.js
  - make lint
  - make test
  - make integration-test
